// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nrbrxvgjuzossfedrqqi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5yYnJ4dmdqdXpvc3NmZWRycXFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNDU5MDQsImV4cCI6MjA2NzkyMTkwNH0.QOCUFOcUcP_p5wEI6jy_YA_TNoVvGc1FJV2NlR89naw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});